hydra:
  run:
    dir: .
  output_subdir: null


planner:
  lambda: 0.5
  mu: 0.3

graph:
  A:
    - [ B, 5.0 ]
    - [ C, 3.0 ]
  B:
    - [ A, 5.0 ]
    - [ D, 2.0 ]
  C:
    - [ A, 3.0 ]
    - [ D, 4.5 ]
  D:
    - [ B, 2.0 ]
    - [ C, 4.5 ]

traffic:
  A-B: 0.2
  A-C: 0.5
  B-D: 0.1
  C-D: 0.3

weather:
  A-B: 0.0
  A-C: 0.1
  B-D: 0.2
  C-D: 0.0

swarm:
  eta: 0.1

# координаты узлов графа
node_coords:
  A: [ 0.0, 0.0 ]
  B: [ 5.0, 0.0 ]
  C: [ 0.0, 3.0 ]
  D: [ 2.0, 2.0 ]

adaptive:
  pid:
    Kp: 1.0
    Ki: 0.1
    Kd: 0.01
  actions:
    - [ Kp, 0.05 ]
    - [ Kp, -0.05 ]
    - [ Ki, 0.01 ]
    - [ Ki, -0.01 ]
    - [ Kd, 0.005 ]
    - [ Kd, -0.005 ]
  alpha: 0.1
  gamma: 0.9
  epsilon: 0.2
  tb_log: ./tensorboard_logs

simulation:
  dt: 0.1
  max_episode_steps: 100
  done_thresh: 0.7
  random_starts: true
  start_range:
    low: [ 0.0, 0.0 ]
    high: [ 5.0, 5.0 ]
  randomize_env: true

reward:
  w_delta: 400.0
  w_step: 0.2
  r_success: 500.0
  collision_penalty: -100.0
  stagnation_penalty: -1.0

training:
  timesteps: 200_000

target_coord: [ 0.0, 0.0 ]
init_positions:
  - [ 3.0, 3.0 ]
  - [ 1.0, 2.0 ]
  - [ 2.0, 3.0 ]
  - [ 3.0, 4.0 ]
  - [ 4.0, 5.0 ]
  - [ 5.0, 6.0 ]
  - [ 6.0, 7.0 ]
  - [ 7.0, 8.0 ]
  - [ 8.0, 9.0 ]
  - [ 9.0, 1.0 ]
  - [ 2.0, 8.0 ]
  - [ 3.5, 1.2 ]
  - [ 7.8, 9.6 ]
  - [ 8.2, 3.1 ]
  - [ 1.1, 7.9 ]
  - [ 5.9, 2.2 ]

